# -*- coding: utf-8 -*-
"""Untitled2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/17NwtcW9aBDdJaQ8wsUEmSYTLyabgSm9v

Практическа работа по теме "Решение задач линейной алгебры и прикладной математики в Python". Работа с библиотекой SCIPY". Выполнил: Деулин.И и Иванюшин.М :3
"""

import numpy as np; from scipy import linalg

a: int = 7
b: int  = 3
y: int  = 1
O: int  = 2
u: int  = 0
v: int  = 5
A = np.array([
    [2, 3+a, 4,],
    [b, y, v,],
    [5, 10*u, -2,]
])
B1 = np.array([
    [b, -3, 4+u,],
    [a, 4, v,],
    [5*u, 10, -2,]
])
C = np.array([
    [-1, 3, 4-v,],
    [2, 1, v,],
    [5, 5-u, -2]
])
D = A*B1*C
print(D)

a: int = 7
b: int  = 3
y: int  = 1
O: int  = 2
u: int  = 0
v: int  = 5

G = np.array([
    [2, 3+a, 4+u, 6,],
    [b+1, y, v, 12,],
    [5, -2, 16, u+1,],
    [2, 7, 11, -6,],
             ])
print(G)

O = linalg.det(G)
print(O)

vec = linalg.eig(G)
print(vec)

from scipy.linalg import *
inf = inv(G)

inf